title: Go Game Jam
description: This is a brief introduction to building a game jam game for beginners.
theme: just-the-docs

url: https://sarahmit.github.io/gogamejam

aux_links:
  gogamejam repository: https://github.com/sarahmit/gogamejam

logo: "/assets/images/gogamejam_logo.png"

# Color scheme
color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red