title: Go Game Jam
description: This is a brief introduction to building a game jam game for beginners.
theme: just-the-docs

url: https://sarahmit.github.io/gogamejam

aux_links:
  Template Repository: https://github.com/sarahmit/gogamejam
