title: Go Game Jam
description: This is a brief introduction to building a game jam game for beginners.
theme: just-the-docs

url: https://sarahmit.github.io/gogamejam

aux_links:
  gogamejam repository: https://github.com/sarahmit/gogamejam

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: blue

logo: "/assets/images/gogamejam-logo.png"

